// scan-images.js — Node.js utility
// Run: node scan-images.js
// Scans KDEF_and_AKDEF/KDEF/ and generates a static image-index.js
// Use this if you want a pre-built index instead of the programmatic one.

var fs   = require('fs');
var path = require('path');

var KDEF_DIR = path.join(__dirname, 'KDEF_and_AKDEF', 'KDEF');
var OUTPUT   = path.join(__dirname, 'image-index.js');

var EMOTION_MAP = {
  AF: 'fear',
  AN: 'anger',
  DI: 'disgust',
  HA: 'happiness',
  NE: 'neutral',
  SA: 'sadness',
  SU: 'surprise'
};

var index = {
  fear: [], anger: [], disgust: [],
  happiness: [], neutral: [], sadness: [], surprise: []
};

var subjects = fs.readdirSync(KDEF_DIR).filter(function (d) {
  return fs.statSync(path.join(KDEF_DIR, d)).isDirectory();
});

subjects.forEach(function (subject) {
  var subDir = path.join(KDEF_DIR, subject);
  var files  = fs.readdirSync(subDir).filter(function (f) {
    return f.toUpperCase().endsWith('.JPG');
  });

  files.forEach(function (file) {
    var name      = file.replace(/\.jpg$/i, '');
    var rest      = name.slice(subject.length); // emotionCode + angle
    var emoCode   = rest.slice(0, 2);
    var angle     = rest.slice(2);
    var emotion   = EMOTION_MAP[emoCode];
    if (!emotion || !angle) return;

    index[emotion].push({
      id:    name,
      path:  'KDEF_and_AKDEF/KDEF/' + subject + '/' + file,
      angle: angle
    });
  });
});

var out =
  '// Auto-generated by scan-images.js — do not edit by hand\n' +
  '// Run: node scan-images.js to regenerate\n' +
  '(function () {\n' +
  '  window.IMAGE_INDEX = ' + JSON.stringify(index, null, 2) + ';\n' +
  '})();\n';

fs.writeFileSync(OUTPUT, out, 'utf8');
console.log('image-index.js written.');
Object.keys(index).forEach(function (k) {
  console.log('  ' + k + ': ' + index[k].length + ' images');
});
